server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_spring
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: userservice
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
#    fetch-registry: false
#    register-with-eureka: false
userService: userService_8001